language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
bundler_args: --without guard
before_script: gem install bundler -v 1.10.6 && sudo service redis-server status && sudo service mongodb status
script: bundle exec rake
services:
  - redis-server
  - mongodb
env:
  - RAILS_VERSION=4.2.5
  - RAILS_VERSION=3.2.21
