language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
bundler_args: --without guard
before_script: sudo service redis-server status && sudo service mongodb status && gem install bundler -v 1.10.6
script: bundle exec rake
services:
  - redis-server
  - mongodb
